repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
        exclude_types: [markdown]
    -   id: trailing-whitespace
        exclude_types: [markdown]
    -   id: requirements-txt-fixer
    -   id: check-json
    -   id: check-yaml
